Feature/js setup
e-sites/fe-boilerplate-poc pull request #8
Opened 2017-11-01 15:23 UTC by bramsmulders

2017-11-01 15:29 UTC, iainvdw requested changes
Yo, check deze comments nog even pl0x ;)

2017-11-01 15:29 UTC, iainvdw commented on assets/js/app.js
> +import './polyfills/core-js';
Polyfills _voor_ alle andere JS inladen pl0x ;)

2017-11-01 15:29 UTC, iainvdw commented on assets/js/app.js
> +import '@e-sites/vestigo';
Vestigo wordt niet ge-init?

Ik had dit verwacht:
```js
import vestigo from '@e-sites/vestigo'
vestigo.init();
```

2017-11-01 15:29 UTC, iainvdw commented on package.json
> +      "tasks": "/tasks",
Waarom /tasks ipv ./tasks?

2017-11-01 15:34 UTC, bramsmulders commented on assets/js/app.js
> +import './polyfills/core-js';
kennie

2017-11-01 15:34 UTC, bramsmulders commented on package.json
> +      "tasks": "/tasks",
omdat gulp dood ging ;)

2017-11-01 16:01 UTC, iainvdw commented on assets/js/app.js
> +import './polyfills/core-js';
Gewoon naar boven katten en voorzien van eslint-ignore comment ding regel stuff

2017-11-02 09:32 UTC, iainvdw approved these changes
Jot!

2017-11-02 09:32 UTC, merged